# Generated by Django 4.1.5 on 2023-01-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property_details',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=255)),
                ('p_addr', models.CharField(max_length=255)),
                ('p_state_name', models.CharField(max_length=255)),
                ('p_state_id', models.IntegerField(max_length=5)),
                ('p_city', models.CharField(max_length=255)),
            ],
        ),
    ]
