# Generated by Django 4.1.5 on 2023-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop_mng_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_details',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='property_details',
            name='p_state_id',
        ),
    ]
